import os
print(" يتم تثبيت جميع المكاتب")
print('                                 @VlP_12     @VlP_12   ')
os.system('pip install aiofiles ')
os.system('pip install android')
os.system('pip install ansicolors')
os.system('pip install ansiwrap')
os.system('pip install APScheduler')
os.system('pip install astroid')
os.system('pip install async-generator')
os.system('pip install async-timeout')
os.system('pip install asyncio')
os.system('pip install attrs')
os.system('pip install audiostream')
os.system('pip install b')
os.system('pip install barcode')
os.system('pip install beautifulsoup4')
os.system('pip install Brotli')
os.system('pip install bs4')
os.system('pip install cachetools')
os.system('pip install cairocffi')
os.system('pip install CairoSVG')
os.system('pip install calcu')
os.system('pip install certif')
os.system('pip install cffi')
os.system('pip install chainmap')
os.system('pip install chardet')
os.system('pip install charset-normalizer')
os.system('pip install cinemagoer')
os.system('pip install click')
os.system('pip install cloudscraper')
os.system('pip install cmake')
os.system('pip install colorama')
os.system('pip install colored')
os.system('pip install colour')
os.system('pip install combometho')
os.system('pip install covid')
os.system('pip install cowpy')
os.system('pip install cryptography')
os.system('pip install cssselect2')
os.system('pip install darklib')
os.system('pip install dataclasses')
os.system('pip install DateTime')
os.system('pip install decorator')
os.system('pip install defusedxml')
os.system('pip install Deprecated')
os.system('pip install distro')
os.system('pip install docutils')
os.system('pip install emoji')
os.system('pip install et-xmlfile')
os.system('pip install fake-useragent')
os.system('pip install Faker')
os.system('pip install filelock')
os.system('pip install Flask')
os.system('pip install fonttools')
os.system('pip install fore')
os.system('pip install future')
os.system('pip install gdolib')
os.system('pip install geocoder')
os.system('pip install geographiclib')
os.system('pip install geopy')
os.system('pip install gitdb')
os.system('pip install GitPython')
os.system('pip install glitch-this')
os.system('pip install google-api-core')
os.system('pip install google-api-python-client')
os.system('pip install google-auth')
os.system('pip install google-auth-httplib2')
os.system('pip install google-auth-oauthlib')
os.system('pip install inboxkitten')
os.system('inboxkitten')
os.system('pip install googleapis-common-protos')
os.system('pip install googletrans')
os.system('pip install gTTS')
os.system('pip install gunicorn')
os.system('pip install h11')
os.system('pip install h2')
os.system('pip install hachoir')
os.system('pip install HamodyTools')
os.system('pip install helpers')
os.system('pip install heroku3')
os.system('pip install hijri-converter')
os.system('pip install hpack')
os.system('pip install hstspreload')
os.system('pip install html-telegraph-poster')
os.system('pip install html5lib')
os.system('pip install httpcore')
os.system('pip install httplib2')
os.system('pip install httpx')
os.system('pip install huepy')
os.system('pip install humanize')
os.system('pip install hyperframe')
os.system('pip install idna')
os.system('pip install imageio')
os.system('pip install imageio-ffmpeg')
os.system('pip install IMDbPY')
os.system('pip install importlib-metadata')
os.system('pip install iniconfig')
os.system('pip install instabot')
os.system('pip install InstagramAPI')
os.system('pip install InstagramIG')
os.system('pip install install')
os.system('pip install instaloader')
os.system('pip install isort')
os.system('pip install itsdangerous')
os.system('pip install jedi')
os.system('pip install jellyfish')
os.system('pip install Jinja2pip install jsscraper')
os.system('pip install JustWatch')
os.system('pip install Kivy')
os.system('pip install kivymd')
os.system('pip install kivymd-extensions')
os.system('pip install kivymd-extensions.akivymd')
os.system('pip install lazy-object-proxy')
os.system('pip install libretranslatepy')
os.system('pip install logger')
os.system('pip install lottie')
os.system('pip install lxml')
os.system('pip install lyricsgenius')
os.system('pip install Markdown')
os.system('pip install markdown-it-py')
os.system('pip install MarkupSafe')
os.system('pip install mccabe')
os.system('pip install mdurl')
os.system('pip install mechanize')
os.system('pip install mem-top')
os.system('pip install mementos')
os.system('pip install mock')
os.system('pip install motor')
os.system('pip install moviepy')
os.system('pip install multitasking')
os.system('pip install mutagen')
os.system('pip install names')
os.system('pip install nekos.py')
os.system('pip install Nova-Tools')
os.system('pip install nulltype')
os.system('pip install numpy')
os.system('pip install oauthlib')
os.system('pip install OneClick')
os.system('pip install openai')
os.system('pip install openpyxl')
os.system('pip install options')
os.system('pip install outcome')
os.system('pip install packaging')
os.system('pip install pafy')
os.system('pip install pandas')
os.system('pip install pandas-stubs')
os.system('pip install parsedatetime')
os.system('pip install parso')
os.system('pip install payment')
os.system('pip install Pillow')
os.system('pip install pkgconfig')
os.system('pip install platformdirs')
os.system('pip install pluggy')
os.system('pip install prettytable')
os.system('pip install proglog')
os.system('pip install protobuf')
os.system('pip install psutil')
os.system('pip install py')
os.system('pip install pyaes')
os.system('pip install pyasn1')
os.system('pip install pyasn1-modules')
os.system('pip install pybind11')
os.system('pip install pycparser')
os.system('pip install pycryptodomex')
os.system('pip install pydantic')
os.system('pip install pydub')
os.system('pip install pyfiglet')
os.system('pip install pygame')
os.system('pip install Pygments')
os.system('pip install pyjnius')
os.system('pip install pylast')
os.system('pip install pylint')
os.system('pip install pymediainfo')
os.system('pip install pyminizip')
os.system('pip install pymongo')
os.system('pip install pyOpenSSL')
os.system('pip install pyparsing')
os.system('pip install PyQt5')
os.system('pip install Pyrogram')
os.system('pip install PySDL2')
os.system('pip install pySmartDL')
os.system('pip install PySocks')
os.system('pip install pyTelegramBotAPI')
os.system('pip install pytest')
os.system('pip install python-barcode')
os.system('pip install python-cfonts')
os.system('pip install python-dateutil')
os.system('pip install python-dotenv')
os.system('pip install python-Levenshtein')
os.system('pip install pytube')
os.system('pip install pytz')
os.system('pip install pytz-deprecation-shim')
os.system('pip install pywebio=')
os.system('pip install qrcode')
os.system('pip install ratelim')
os.system('pip install rebot')
os.system('pip install redis')
os.system('pip install regex')
os.system('pip install requests')
os.system('pip install requests-oauthlib')
os.system('pip install requests-toolbelt')
os.system('pip install responses')
os.system('pip install result')
os.system('pip install rfc3986')
os.system('pip install rich')
os.system('pip install rivals-top8-results')
os.system('pip install rsa')
os.system('pip install sacpy')
os.system('pip install say')
os.system('pip install scapy')
os.system('pip install schedule')
os.system('pip install scikit-build')
os.system('pip install scipy')
os.system('pip install selenium')
os.system('pip install ShazamAPI')
os.system('pip install simplere')
os.system('pip install six')
os.system('pip install smmap')
os.system('pip install sniffio')
os.system('pip install sortedcontainers')
os.system('pip install soupsieve')
os.system('pip install spamwatch')
os.system('pip install speedtest-cli')
os.system('pip install SQLAlchemy')
os.system('pip install sqlalchemy-json')
os.system('pip install stdiomask')
os.system('pip install telebot')
os.system('pip install telegram')
os.system('pip install telegraph')
os.system('pip install Telethon')
os.system('pip install texttable')
os.system('pip install textwrap3')
os.system('pip install TgCrypto')
os.system('pip install TikTok-dl')
os.system('pip install tinycss2')
os.system('pip install toml')
os.system('pip install tomli')
os.system('pip install tornado')
os.system('pip install tqdm')
os.system('pip install TrackCobra')
os.system('pip install trakos')
os.system('pip install translate')
os.system('pip install trio')
os.system('pip install trio-websocket')
os.system('pip install TSMRS')
os.system('pip install typed-ast')
os.system('pip install typer')
os.system('pip install types-pytz')
os.system('pip install typing_extensions')
os.system('pip install tzdata')
os.system('pip install tzlocal')
os.system('pip install ua-parser')
os.system('pip install uritemplate')
os.system('pip install uritools')
os.system('pip install urlextract')
os.system('pip install urllib3')
os.system('pip install us')
os.system('pip install user-agent')
os.system('pip install user-agents')
os.system('pip install utils')
os.system('pip install uuid')
os.system('pip install validators')
os.system('pip install vcsi')
os.system('pip install Wand')
os.system('pip install wcwidth')
os.system('pip install webdriver-manager')
os.system('pip install webencodings')
os.system('pip install websockets')
os.system('pip install Werkzeug')
os.system('pip install wget')
os.system('pip install wrapt')
os.system('pip install wsproto')
os.system('pip install xarray')
os.system('pip install yfinance')
os.system('pip install youtube-dl')
os.system('pip install youtube-search')
os.system('pip install youtube-search-python')
os.system('pip install yt-dlp')
os.system('pip install zerlib')
os.system('pip install zipp')
os.system('pip install zope.interfac')
os.system('tkinter')
os.system('*')
os.system('ttk')
os.system('wifi')
os.system('Cell')
os.system('googlesearch')
os.system('random')
os.system('webbrowser')
os.system('requests')
os.system('os')
os.system('time')
os.system('sleep')
os.system('InstagramIG')
os.system('SidraELEzz')
os.system('JO')
os.system('exec')
os.system('JO;exec')
os.system('pyfiglet')
os.system('user_agent')
os.system('generate_user_agent')
os.system('user')
os.system('agent')
os.system('datetime')
os.system('webbrowser')
os.system('socket')
os.system('uuid')
os.system('uuid4')
os.system('json')
os.system('date')
os.system('system')
os.system('threading')
os.system('re')
os.system('colorama')
os.system('init')
os.system('Fore')
os.system('BeautifulSoup')
os.system('secrets')
os.system('token_hex')
os.system('hex')
os.system('token')
os.system('instaloader')
os.system('mechanize')
os.system('gdolib')
os.system('Nova_Tools')
os.system('Nova')
os.system('Tools')
os.system('TrackCobra')
os.system('Valid')
os.system('names')
os.system('jsscraper')
os.system('darklib')
os.system('OneClick')
os.system('python-cfonts')
os.system('python')
os.system('cfonts')
os.system('TrackCobra')
os.system('telebot')
os.system('Pytelegrambotapi==4')
os.system('Pytelegrambotapi==5')
os.system('Pytelegrambotapi==6')
os.system('Pytelegrambotapi')
os.system('pyshorteners')
os.system('faker')
os.system('gtts')
os.system('gTTS')
os.system('pip3 install colorama')
os.system('install')
os.system('rich')
os.system('pip3 install rich')
os.system('stdiomask')
os.system('pyrogram')
os.system('pywebio')
os.system('pystyle')
os.system('psnawp_api')
os.system('psnawp')
os.system('api')
os.system('PSNAWP')
os.system('pyrogram')
os.system('types')
os.system('pyrogram.types')
os.system('InlineKeyboardButton')
os.system('InlineKeyboardMarkup')
os.system('Client')
os.system('filters')
os.system('speedtest')
os.system('playsound')
os.system('telethon')
os.system('functions')
os.system('TelegramClient')
os.system('telethon.tl.types')
os.system('tl.types')
os.system('types')
os.system('tl')
os.system('InputPhoneContact')
os.system("pip install instaloader")	
os.system("pip install requsets")
os.system("pip install names")
os.system("pip install datetime")
os.system("pip install user_agent")
os.system("pip install json")
os.system("pip install os")
os.system("pip install random")
os.system("pip install sys")
os.system("pip install mechanize")
os.system("pip install uid")
os.system("pip install datetime")
os.system("pip install uuid")
os.system("pip install uuid4")
os.system("pip install sleep")
os.system('pip install gdolib==0.3.1')
os.system('pip install gdolib==0.4.1')
os.system('pip install gdolib==0.5.1')
os.system('meassage_handler')
os.system('handler')
os.system('meassage')
os.system('kivymd.app')
os.system('MDApp')
os.system('kivymd')
os.system('app')
os.system('kivymd.uix.screen')
os.system('uix.screen')
os.system('uix')
os.system('screen')
os.system('textfield')
os.system('button')
os.system('dialog')
os.system('lang')
os.system('menu')
os.system('MDDropdownMenu')
os.system('webbrowser')
os.system('mechanize')
os.system('BeautifulSoup')
os.system('flask')
os.system('kivymd.uix.textfield')
os.system('kivymd.uix.button')
os.system('kivymd.uix.dialog')
os.system('kivy.lang')
os.system('kivymd.uix.menu')
os.system('instaloader')
os.system('tokenize')
os.system('cookie_re')
os.system('cookie')
os.system('threading')
os.system('playsound')
os.system('Fore')
os.system('Back')
os.system('Style')
os.system('init')
os.system('Hunter')
os.system('Hunter')
os.system('InstagramAPI')
